---
title: "Initial Regressions"
author: "Xie Lihong, Zhang Zhenglin"
output:
  pdf_document:
    toc: yes
editor_options:
  markdown:
    wrap: sentence
---
# Necessary libraries

```{r message=FALSE,warning=FALSE}
library(knitr)
library(ggplot2)
theme_set(theme_bw())
library(emmeans)
library(multcomp)
library(PLS205)
library(lme4)
library(lmerTest)
library(multcompView)
library(car)
library(Rmisc) 
library(dplyr) #https://r4ds.had.co.nz/ (Chapter 3, Chapter 5, look at filter and select)
# https://bookdown.org/ansellbr/WEHI_tidyR_course_book/
library(stringr) 
library(data.table)
library(GGally)
library(formatR)
library(readxl)
library(openxlsx)
library(zoo)
library(dplyr)
library(tidyr)
library(zoo)
```

# Read Excel daily flux values from obtained from Li-Cor and GC methodologies

```{r}
raw <- read_excel("../data/initial_Database.xlsx", sheet = 1)

licor$Plot <- as.factor(licor$Plot)

GC <- read_excel("../Computed_Flux/GC_2025_CH4_N2O_Flux.xlsx", sheet = 1) %>%
            mutate(Treatment = factor(str_sub(Plot, 2)))

str(licor)
str(GC)

#flux %>%
#  summarise(n_dates = n_distinct(Date))
```